[package]
name = "obsidian-rust-plugin"
version = "0.1.0"
authors = ["Stephen Solka <solka@angel.co>"]
edition = "2018"

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
features = ["web_sys_unstable_apis"]

[profile.dev]
features = ["web_sys_unstable_apis"]


[dependencies]
wasm-bindgen = { version = "^0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.22"
js-sys = "0.3.49"
url = "1"
html2md = "0.2.10"
thiserror = "1.0.24"
frontmatter = "^0.4"
yaml-rust = "^0.4"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
futures = "^0.3.14"
fancy-regex = "0.10.0"
lazy_static = "1.4.0"
scraper = "0.13.0"
web-sys = { version = "0.3.57", features = ["Element", "Document", "EventTarget", "Window","Clipboard","Navigator","console", "Permissions"]}
select = "0.6.0"
linkify = "0.9.0"

[dependencies.readability]
git = "https://github.com/trashhalo/readability.git"
version = "^0"
default-features = false
